language: ruby
matrix:
  include:
    - rvm: 2.0.0
      gemfile: spec/Gemfile.rails-4.2
    - rvm: 2.1.8
      gemfile: spec/Gemfile.rails-4.2
    - rvm: 2.2.4
      gemfile: spec/Gemfile.rails-4.2
    - rvm: 2.2.4
      gemfile: spec/Gemfile.rails-5.0
    - rvm: 2.3.0
      gemfile: spec/Gemfile.rails-4.2
    - rvm: 2.3.0
      gemfile: spec/Gemfile.rails-5.0
sudo: false
